image:https://travis-ci.org/qaware/cloudcontrol.svg?branch=master["Build Status", link="https://travis-ci.org/qaware/cloudcontrol"]
image:https://img.shields.io/badge/license-MIT%20License-blue.svg["MIT License", link=https://github.com/qaware/cloudcontrol/blob/master/LICENSE"]

= Cloud Control

Remote control a Kubernetes, Marathon, Vamp.io or Docker Swarm cluster using a
Novation Launch Control MIDI controller.

== Usage

Using the Cloud Control device is easy. First, connect the device via USB with you machine.
Neither Windows nor Mac need an USB driver for it.

If you use the precompiled binaries, simply
extract the ZIP archive and execute `bin/cloudcontrol`.

If you want to run from source, you have to compile everything first and then run using Gradle.
```bash
$ ./gradlew build
$ ./gradlew run
```

== Configuration

[cols="1,1,2", options="header"]
|===
| Name
| Default Value
| Description

| cluster.orchestrator
| kubernetes
| Determines the Orchestrator to use. Currently only `kubernetes` is supported.

| kubernetes.namespace
| default
| The Kubernetes namespace to scan for deployments.
|===


== Action Buttons

Currently only the knobs of the top row can be used to scale a deployment
up or down. Simply turn it in the desired direction. If you scale a deployment to
zero, the button will turn yellow. Otherwise the button is green.

== Labels

To use the CloudControl device with you deployments you need to use labels to
configure things such as the location and color on the device. The following
labels are supported.

[cols="1,1,2", options="header"]
|===
| Name
| Values
| Description

| cloudcontrol.enabled
| `true` or `false`
| Is this deployment controlled by the device.
If `false` the deployment will be ignored.

| cloudcontrol.index
| 0..15
| The index of the deployment on the CloudControl device.
Index 0..7 is on the Factory bank, index 8..15 on the User bank.
|===

== References

* https://novationmusic.de/launch/launch-control[Novation Launch Control]
* https://d19ulaff0trnck.cloudfront.net/sites/default/files/novation/downloads/6958/launch-control-programmers-reference-guide.pdf[Launch Control Programmers reference guide]
* http://docs.oracle.com/javase/tutorial/sound/TOC.html[Java Sound Tutorial]
* http://docs.oracle.com/javase/tutorial/sound/MIDI-messages.html[Transmitting and Receiving MIDI Messages]
* https://docs.oracle.com/javase/8/docs/api/javax/sound/midi/package-summary.html[javax.sound.midi API]

== Maintainer

M.-Leander Reimer (@lreimer), <mario-leander.reimer@qaware.de>

== License

The software and documentation is provided under the MIT open source license,
read the `LICENSE` file for details.
